[webservers]
hexlet-6-web-1 ansible_host=89.169.158.116 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/hexlet-6-ansible
hexlet-6-web-2 ansible_host=51.250.3.71 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/hexlet-6-ansible
