---
- name: Configure and deploy Redmine
  hosts: all
  become: true
  gather_facts: true
  serial: 1
  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 3600

  roles:
    - role: docker
      tags:
        - prepare

    - role: redmine
      tags:
        - deploy

    - role: monitoring
      tags:
        - monitoring
