---
- name: Configure and deploy Redmine
  hosts: all
  become: true
  gather_facts: true
  serial: 1
  module_defaults:
    ansible.builtin.apt:
      cache_valid_time: 3600

  pre_tasks:
    - name: Prepare package prerequisites
      ansible.builtin.import_role:
        name: docker
        tasks_from: prerequisites
      tags:
        - prepare

    - name: Stage monitoring signing keys
      ansible.builtin.import_role:
        name: monitoring
        tasks_from: keys
      tags:
        - monitoring

  roles:
    - role: docker
      tags:
        - prepare

    - role: redmine
      tags:
        - deploy

    - role: monitoring
      tags:
        - monitoring
