---
- name: Validate Datadog deployment variables
  ansible.builtin.assert:
    that:
      - datadog_api_key | length > 0
      - datadog_site is defined
      - datadog_site | length > 0
      - datadog_agent_version is defined
      - datadog_agent_version | length > 0
    fail_msg: >-
      Required Datadog site, version, or Vault variables are missing.
  when: "'webservers' in group_names"
  no_log: true
  tags:
    - monitoring

- name: Install and configure Datadog Agent
  ansible.builtin.import_role:
    name: datadog.dd.agent
  vars:
    datadog_apt_default_keys:
      - key: DATADOG_APT_KEY_CURRENT
        value: >-
          file:///var/cache/hexlet-6-datadog-keys/DATADOG_APT_KEY_CURRENT.public
      - key: A2923DFF56EDA6E76E55E492D3A80E30382E94DE
        value: >-
          file:///var/cache/hexlet-6-datadog-keys/DATADOG_APT_KEY_382E94DE.public
      - key: D75CEA17048B9ACBF186794B32637D44F14F620E
        value: >-
          file:///var/cache/hexlet-6-datadog-keys/DATADOG_APT_KEY_F14F620E.public
      - key: 5F1E256061D813B125E156E8E6266D4AC0962C7D
        value: >-
          file:///var/cache/hexlet-6-datadog-keys/DATADOG_APT_KEY_C0962C7D.public
      - key: D18886567EABAD8B2D2526900D826EB906462314
        value: >-
          file:///var/cache/hexlet-6-datadog-keys/DATADOG_APT_KEY_06462314.public
  when: "'webservers' in group_names"
  no_log: true
  tags:
    - monitoring
