---
- name: Prepare package prerequisites
  ansible.builtin.import_tasks: prerequisites.yml
  tags:
    - prepare

- name: Install Docker SDK for Python
  ansible.builtin.import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
        version: "7.2.0"
        extra_args: --break-system-packages
  tags:
    - prepare

- name: Install Docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  vars:
    docker_add_repo: false
    docker_install_compose_plugin: false
    docker_packages:
      - docker.io
    docker_users:
      - "{{ ansible_user | default(ansible_facts['user_id']) }}"
  tags:
    - prepare
